//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cherkova_va.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int ID { get; set; }
        public Nullable<int> vacancy { get; set; }
        public Nullable<int> CV { get; set; }
        public string Status { get; set; }
    
        public virtual CV CV1 { get; set; }
        public virtual Vacancy Vacancy1 { get; set; }
    }
}
